import {
  PdkAction,
  PdkAlertComponent,
  PdkAutosuggest,
  PdkBackLink,
  PdkBreadcrumbs,
  PdkButton,
  PdkCheckBox,
  PdkContextPanelComponent,
  PdkCore,
  PdkDateInput,
  PdkDetailsSummary,
  PdkDividerComponent,
  PdkErrorSummaryComponent,
  PdkForm,
  PdkGrid,
  PdkInsetTextComponent,
  PdkPaginationComponent,
  PdkPanelComponent,
  PdkRadio,
  PdkSelectComponent,
  PdkServiceNavigation,
  PdkTable,
  PdkTextInput,
  PdkTimeInputComponent,
  PdkWarningTextComponent,
  PdkInput
} from '@cpp/pdk';

export const PdkComponents = [
  PdkCheckBox,
  PdkDateInput,
  PdkTextInput,
  PdkInput,
  PdkCore,
  PdkServiceNavigation,
  PdkGrid,
  PdkButton,
  PdkTable,
  PdkDetailsSummary,
  PdkBackLink,
  PdkBreadcrumbs,
  PdkForm,
  PdkAction,
  PdkAutosuggest,
  PdkRadio,
  PdkAlertComponent,
  PdkSelectComponent,
  PdkDividerComponent,
  PdkPanelComponent,
  PdkContextPanelComponent,
  PdkTimeInputComponent,
  PdkPaginationComponent,
  PdkInsetTextComponent,
  PdkWarningTextComponent,
  PdkErrorSummaryComponent
] as const;
